### ISSUE TITLE
NullError when inspector tries to display a generic list of BaseReference

### ISSUE THREAD

**Issue by TheRealDorcan** [DanielEverland/ScriptableObject-Architecture#105]
Hello ! 

Small bug I fixed on my side: Basically, the inspector can't display a list of references because it generates a null error.
`List<StringReference> listOfStringReferences;`

(Arrays work fine)
`StringReference[] arrayOfStringReferences;`

The error:
`NullReferenceException: Object reference not set to an instance of an object
BaseReferenceHelper.GetValueType (System.Reflection.FieldInfo fieldInfo) (at Editor/BaseReferenceHelper.cs:31)`

Here's my fix in BaseReferenceHelper.cs :
```
    public static Type GetValueType(FieldInfo fieldInfo)
    {
		 . . .
		if (referenceType.IsGenericType)
		{
			referenceType = referenceType.GetGenericArguments()[0];
		}
		else if (referenceType.IsArray)
		{
			referenceType = referenceType.GetElementType();
		}
		. . .
    }
```

Anyway, thanks a lot for all the quality hard work you put in this project! :)

Daniel

**Comment by DanielEverland** [comment]
Thanks for the kind words and a snippet of your fix! I'll fix this in master sometime when I can find the time :)

**Comment by DanielEverland** [comment]
Fixed. Thanks for creating the issue and letting me know how you fixed it :)
