### ISSUE TITLE
Event Listeners fail on instantiated prefabs

### ISSUE THREAD

**Issue by theiviaxx** [DanielEverland/ScriptableObject-Architecture#106]
[forissues.zip](https://github.com/DanielEverland/ScriptableObject-Architecture/files/4084501/forissues.zip)

I've attached a test project that includes the Addressables package and the SO architecture files.  When run, it will load 3 different types of assets via addressables and log their name and instantiate the prefab, this is just to show addressables working.  Clicking the UI button should raise the BoolGameEvent and log an error with the value.  However nothing happens.

This works as expected in the editor, but not in a build (Windows or Android).
Unity 2019.1.6f1

**Comment by DanielEverland** [comment]
Thanks for the report, I'll look into it when I can find the time :)

**Comment by theiviaxx** [comment]
i'll try to dig into it more this weekend to provide more details

**Comment by DanielEverland** [comment]
Thanks, any help would be much appreciated.

**Comment by theiviaxx** [comment]
I dont think this is an issue with this package, its an addressables issue.  It looks like the BoolGameEvent asset i have is different (different instance id and hash code) when used in a scene vs used in a loaded prefab.
