### ISSUE TITLE
Various improvements

### ISSUE THREAD

**Issue by rafaelbenavent** [DanielEverland/ScriptableObject-Architecture#107]
I hope it's OK for me to make multiple suggestions in a single post.

1. Variables. Variables are just strange. They inherit from GameEvent which makes no sense because a Variable is not an Event. But also, you can't raise them using their actual value (due to the inheritance of course).
Proposed change: Add a UnityEvent<T> onChanged to each variable of type T.
Example: a BoolVariable would have a BoolUnityEvent onChanged.
This would be a rather trivial change to make and could be **non-breaking**: leave the current BaseVariable'<'T> as is, and add a new BaseVariable<TVariable, TUnityEvent> class. Refactor Variables to derive from the new BaseVariable<T, U>. A no argument UnityEvent could be added to the BaseVariable'<'T>. That way, users inheriting from BaseVariable'<'T> would get bonus functionality while having their code remain unbroken.
Users would then be free to decide what happens when the variable changes: do they raise an event? Do they raise multiple? Do they do nothing? Do they call another method on another ScriptableObject? It's up to them.

Second suggestion: MonoBehaviour & Unity API event event listeners. What I mean is right now there are many GameEventListeners. A MonoBehaviour message listen would look something like this:

public class StartEventListener : MonoBehaviour
    public UnityEvent onStart;
    private void Start() { onStart.Invoke() }

Personally, I use Start, OnEnable, OnDisable, and SceneActivation/Deactivation.

**Comment by DanielEverland** [comment]
No worries regarding having multiple requests per post :)

Regarding variables inheriting GameEvent, I totally agree, semantically this is very weird. Unfortunately, it's a necessary evil due to Unity's serialization scheme, since it's important that you can subscribe to a variable using a GameEventListener, which requires variables to inherit GameEvent. This _might_ be fixable using custom serialization, which we've discussed as a [possiblity for v2.0](https://github.com/DanielEverland/ScriptableObject-Architecture/issues/100). I'm not 100% sure since it would have to play nice with Unity's UI as well. Changing it to a has-a relationship would definitely be breaking in the current state, though.

I like your second suggestion, I'll add it to my to-do list :)

**Comment by rafaelbenavent** [comment]
Why is it important for a GameEventListener to listen to a variable when it can't even get its value?
Removing it's inheritance from GameEvent would breaking change *but* you could still add a UnityEvent(<'T>) field as I described in the OP which would not be a breaking change. That way, it could still be raised and listened to. :)

**Comment by DanielEverland** [comment]
Not all events are typed, and sometimes it doesn't matter what the new value is, simply that it has been changed. For instance, you could have a variable that references the player's current weapon, anf whenever it changes, you play an animation in the UI.

I'm not going to make a change that would break systems when someone updates simply for semantics. If you want to subscribe to an event and get a typed callback, you can use a GameEventListener component :)

**Comment by DanielEverland** [comment]
I think a compromise might be a good solution. Keep the current inheritance, but add a typed UnityEvent. It wouldn't work in the editor, but you'd be able to get a typed callback from a variable using code

Does that sound good to you? :)

**Comment by rafaelbenavent** [comment]
It would still work. I tested it and it's fine:

![image](https://user-images.githubusercontent.com/17901463/73226353-dcf9ad80-41c3-11ea-8bd7-047a28a5f6d1.png)

So I made the changes very quickly but here's what I did:

1. New class:
`
using UnityEngine;

    public abstract class BaseVariableWithEvent<T, U> : BaseVariable<T> where U : UnityEngine.Events.UnityEvent<T>
    {
        [SerializeField]
        private U _onChanged;
    }
`
2. New variable that inherits from it:

`
using ScriptableObjectArchitecture;
using UnityEngine;

[CreateAssetMenu]
public class TestVariable : BaseVariableWithEvent<int, IntUnityEvent>
{
}
`

3. New editor class:

`using UnityEngine;
using UnityEditor;

    [CustomEditor(typeof(BaseVariableWithEvent<,>), true)]
    public class BaseVariableTUEditor : BaseVariableEditor
    {

        public override void OnInspectorGUI()
        {
            base.OnInspectorGUI();
            EditorGUILayout.PropertyField(serializedObject.FindProperty("_onChanged"));
        }
        
    }
`

**Comment by DanielEverland** [comment]
You haven't changed the inheritance, so it should indeed be backwards compatible. Thanks for clarifying and suggesting the improvement, I'll implement it when I can find the time :)

**Comment by rafaelbenavent** [comment]
One last suggestion if I may. Currently, fields added to a class deriving from BaseVariable will not be drawn in the inspector. My suggestion is to reflect upon the type hierarchy and draw all public fields or private fields with the serializefield attribute. This way, even if I add my own fields like a DisplayName field, it will get drawn without me having to write a new editor for it.

Now, I mentioned reflection above because that's the way I did it before but there might be other ways like getting all serialized properties from serializedobject or using drrawpropertiesexcluding method.

**Comment by DanielEverland** [comment]
Sure thing, I've implemented this before. I'll add it to the list :)
