### ISSUE TITLE
Developer description update

### ISSUE THREAD

**Issue by DanielEverland** [DanielEverland/ScriptableObject-Architecture#111]
![image](https://user-images.githubusercontent.com/5272590/73469663-03b41180-4387-11ea-9a59-fae4fcc7fa4a.png)

1. It's currently clipping its header. Tested in 2019.3, but might happen in older versions as well.
2. Update its background so it looks like a text area

**Comment by DanielEverland** [comment]
Developer descriptions will be removed in 1.6.5

**Comment by shekit** [comment]
Hey, why are developer descriptions being removed?
