### ISSUE TITLE
Bug - Incorrect copy/paste in GameEventBase

### ISSUE THREAD

**Issue by shekit** [DanielEverland/ScriptableObject-Architecture#113]
https://github.com/DanielEverland/ScriptableObject-Architecture/blob/d9c181127007355b2066a8c2ae79de74ff887b13/Assets/SO%20Architecture/Events/Game%20Events/GameEventBase.cs#L111

I think it should be _actions.Count

**Comment by DanielEverland** [comment]
Thanks for the report, I've fixed the issue :)
