### ISSUE TITLE
Question - Need for implementing the IEnumerable interface?

### ISSUE THREAD

**Issue by shekit** [DanielEverland/ScriptableObject-Architecture#114]
https://github.com/DanielEverland/ScriptableObject-Architecture/blob/ff3f5bd051586bbd59e891ee65a4aebce8076689/Assets/SO%20Architecture/Collections/BaseCollection.cs#L6

Hey, i have been studying the code base but wasnt too sure about the need for implementing this interface in the BaseCollection.cs and Collection.cs classes? Could you elaborate on this?

**Comment by DanielEverland** [comment]
Sure thing.

`IEnumerable` lets you iterate over an object in a `foreach` loop. For instance:

```csharp
foreach (GameObject gameObject in gameObjectCollection)
{
    // Do stuff here
}
```

You can read more about it here: https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerable?view=netframework-4.8

Hope that answers your question :)
