### ISSUE TITLE
Question - Need for Actions List in GameEvents?

### ISSUE THREAD

**Issue by shekit** [DanielEverland/ScriptableObject-Architecture#115]
https://github.com/DanielEverland/ScriptableObject-Architecture/blob/ff3f5bd051586bbd59e891ee65a4aebce8076689/Assets/SO%20Architecture/Events/Game%20Events/GameEventBase.cs#L58

My understanding was that this line is essential to listen to the Game Variable events. I am still not quite sure how listeners subscribe to the variable events. However I went ahead and commented out all references to the <System.Action> lists (both typed and normal) in the GameEventBase class but the system still works.

What are the _typedActions and _actions lists in the GameEventBase used for? 

Thanks!

**Comment by DanielEverland** [comment]
There are two ways you can subscribe to an event:

1. Using event listeners, which require the subscriber to pass an object which inherits `IGameEventListener` - if you're subscribing through the editor, this is how it's handled
2. Using actions, which is a type of delegate. This is only used if you want to subscribe manually, and allows you to fully utilize all of the functionality of C# delegates - it will, for instance, allow you to subscribe using lambda expressions.

```csharp
gameEvent.AddListener(() => { /* Do stuff here */ });
```

You can read more about delegates here: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/delegates/

Hope that answers your question :)
