### ISSUE TITLE
Question: How to use this architecture with multiple instances of same prefab

### ISSUE THREAD

**Issue by Spyrou42** [DanielEverland/ScriptableObject-Architecture#118]
Hello,
Thanks for sharing this pattern :). I just saw the Unite2017 talk, I wanted to try the SO modular solution and I was very happy to see that someone already did a package.

I am just wondering how do you implement this system with multiple instances of the same prefab. Let's say you have one player and X enemies. Each enemy has health. If their health is not full, a healthbar is displayed on top of the enemy.

Following the Unite talk and the documentation here, I will need X FloatReference files, one for each enemy.

In the comment section of his talk (https://www.youtube.com/watch?v=raQ3iHhE_Kk&lc=Ugy4IB3QnrE-vTbiXL94AaABAg.8sEJYdF6DIS8sPN93YiCK7) , Ryan said that this pattern is not suited to solve this problem.

In a reddit post on this subject, a person suggested to use the FloatCollection to keep track of all enemies. But isn't this breaking the modular ability of the prefab ?

Other people suggested to create instance of the SO.

I wonder if you have found a way to solve this problem ?

Best regards,

**Comment by DanielEverland** [comment]
As Ryan mentioned, this pattern is not elegant in solving what you're describing.

Instead, I recommend using a more conventional approach. You could, however, setup your healthbar prefab with a FloatReference variable, and then during runtime, instantiate a FloatVariable per enemy, which can then be assigned to each enemy's healthbar's FloatReference.

This has the full benefit of being able to debug the healthbar using the editor, while still having per-instance data, and making sure each system is modular.

Hope that helps answer your question :)

**Comment by Spyrou42** [comment]
Thanks for your answer.
I found a way to adapt it with Monobehaviours instead of SO. I'll use the SO for more global data :).
