### ISSUE TITLE
Using range attribute

### ISSUE THREAD

**Issue by alexanderperrin** [DanielEverland/ScriptableObject-Architecture#121]
Hey there,

Loving this framework so far. Exactly what I've been looking for.

Is there a straightforward way I could use for adding a RangeAttribute onto a FloatVariable? Or is this something I could implement myself?

Thanks!

**Comment by DanielEverland** [comment]
Easiest way would be to create a new type of variable with an editor that uses a range field :)

**Comment by alexanderperrin** [comment]
Awesome! I'll give this a go. Thank you :)

**Comment by DanielEverland** [comment]
No problem!
