### ISSUE TITLE
Why collection has check before Add?

### ISSUE THREAD

**Issue by xvnnnk** [DanielEverland/ScriptableObject-Architecture#122]
`Collection` is supposed to be a list. Lists don't and should not have problem with duplicate entries.
I believe this line should be removed:
https://github.com/DanielEverland/ScriptableObject-Architecture/blob/d8273869eadd3a5c2198f6f62900ca34b7cb7669/Assets/SO%20Architecture/Collections/Collection.cs#L42

If someone needs list of unique values, they can use `Contains` method before `Add`. But the check should not be mandatory.

**Comment by DanielEverland** [comment]
I agree, this should be removed.

**Comment by JohnyBro** [comment]
I agree

**Comment by tuleky** [comment]
I too agree.

**Comment by DanielEverland** [comment]
Fixed in 8a319aa. Thanks for the bug report, I apologize for it taking this long to fix. I've been really busy :)
