### ISSUE TITLE
Icons rendering on GameObjects

### ISSUE THREAD

**Issue by seanxfitz** [DanielEverland/ScriptableObject-Architecture#126]
In the both the Game and Scene view, prefabs that have event listeners on them display the icon of that type of event listener when they are not selected in the inspector. Any idea why this happens/how to stop it? I'm guessing this is some kind of debug feature but I can't figure it out. Installed from Unity Package Manager instructions, running on 2019.3.0f6.

Example - icon showing up on an object in scene 
![IconRendering](https://user-images.githubusercontent.com/22731611/80667970-917ac800-8a6e-11ea-8b68-c61dd96e1611.PNG)

**Comment by Robert-Oost** [comment]
Do you have Gizmos set to visible? I think you're right about the debugging feature, it's probably using Gizmos.DrawIcon to make it happen.

**Comment by seanxfitz** [comment]
You know I thought I tried that already, seems obvious now hah but that's what fixed it. Thank you @Robert-Oost !
