### ISSUE TITLE
How to write event and listener with custom data?

### ISSUE THREAD

**Issue by varfare** [DanielEverland/ScriptableObject-Architecture#127]
Wiki is a little bit sparse on how to actually implement my own event dispatcher and listener where custom data is being passed. I have a scriptable object which I want to pass in my own event. Seems simple but I am getting type issues. Not quite sure what I am doing wrong... Game.Roadside.Biome is just a ScriptableObject. I am probably missing something very, very obvious. I would welcome a little bit of help and just some more examples of custom object type event dispatch/listener, maybe with a complete code example as well (such as DamageDealerWithEvent but target is an actual argument of the event?). Cheers!

`ArgumentException: Object of type 'UnityEngine.Object' cannot be converted to type 'Game.Roadside.Biome'.
System.RuntimeType.CheckValue (System.Object value, System.Reflection.Binder binder, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)`

**Comment by Monsoonexe** [comment]
Go to CodeGeneration (in top row of Unity Editor, I believe, maybe ScriptableObject Architecture -> CodeGeneration), and then create a new Event and Response (a Response is a typed UnityEvent) for your type (probably Biome). You may need to manually edit the generated code files to add namespaces (unless that issue has been fixed) [using Game.Roadside;].

Hope this helps.

**Comment by DanielEverland** [comment]
Yep, Monsoonexe's suggestion is the recommended way to do so. Let me know if you still need help :)
