### ISSUE TITLE
Adding Event name to the title of Event Listener scripts in the Editor

### ISSUE THREAD

**Issue by mutp** [DanielEverland/ScriptableObject-Architecture#130]
Hello,

I'm looking for a way to add the selected Event's name to the title of a Game Event Listener in the Editor. This will make it easier to work in the Editor with many event listener on a Gameobject.
This would work the same way as how the Mesh Filter script works in the editor. Once you select a mesh, the name of the mesh appears in the title of the script.

**Comment by DanielEverland** [comment]
Would be really cool, but as far as I can tell this is not possible.

https://forum.unity.com/threads/can-i-change-a-components-inspector-title-bar-text.959682/
