### ISSUE TITLE
GameEventListenerEditor losing it's styling after Odin import into project

### ISSUE THREAD

**Issue by mutp** [DanielEverland/ScriptableObject-Architecture#131]
Hi,

After I import Odin into my project, the `GameEventListenerEditor` scripts stop working so any script derived from `GameEventListener` losing it's styling in the editor. I suspect it's because of generics and serializing them, but I'm not sure.

In GameEventListenerEditor, if I make it 
    `[CustomEditor(typeof(GameEventListener), true)]`
from this,
    `[CustomEditor(typeof(BaseGameEventListener<,>), true)]`

Then it works. Any idea how I can fix this with Odin in my project?

**Comment by DanielEverland** [comment]
Sorry, I don't have experience using Odin. I'm not sure why it interferes with the drawer. If someone else fixes this with a PR I'm open to implementing it

**Comment by simonbucher** [comment]
I had the same issue. I solved it by changing the settings of the Odin Inspector.

1. Open Settings from Odin Inspector
2. Go to "Editor Types"
3. In Draw for... - deselect ScriptableObjectArchitecture
<img width="1012" alt="Bildschirmfoto 2021-04-04 um 23 07 32" src="https://user-images.githubusercontent.com/46404021/113521634-f9992e80-959a-11eb-833f-1355d0039ace.png">

**Comment by mutp** [comment]
This worked, thanks! Closing the issue.
