### ISSUE TITLE
Cannot reproduce base tutorial

### ISSUE THREAD

**Issue by sebastienwood** [DanielEverland/ScriptableObject-Architecture#132]
Hi !
I've been trying to follow the tutorial (https://github.com/DanielEverland/ScriptableObject-Architecture/wiki/Quick-Start) on References for PlayerCurrentHealth. However, I can't manage to raise the event when the game object health reaches 0.
I am using Unity latest release (LTS version).

**Comment by sebastienwood** [comment]
To be precise, I can raise the callback in debug mode and it works fine. Only issue is that the event  is not raised when the FloatVariable changes.

**Comment by randypanopio** [comment]
I just imported into a new project, it does seem like changing the variable from the inspector no longer raises the event. Sucks as I want to pass of designer debugging through editing those variables. Might want to change the title to that instead.

**Comment by vicenterusso** [comment]
+1 here 1.6.4 triggers the event, but 1.7 doesnt. Also, can't install 1.7 from package manager

**Comment by kamend** [comment]
Same problem here, using Unity 2020.1.1.

**Comment by pixellllman** [comment]
+1 Same issue: SO-A Version 1.7.0, Unity Version 2019.2.12f1

**Comment by HenningKarlsson** [comment]
Same here.

SO-A version 1.7.0 unable to raise the event from change in floatReference.
- Unity 2020.1.17 Confirmed with clean project.
- Unity 2020.2.0 Confirmed with clean project.
- Unity 2019.4.16 (LTS) Confirmed with clean project.

@DanielEverland

**Comment by seoyeon01** [comment]
Is the problem simply a floatReference? I wonder how other users have solved this problem and are using it. In 1.6.4, the GUI is broken and there are issues in the release log of 1.7.0; 1.6.4 has this issue. It has been 7 months since the issue was opened. Are the others still using 1.6.4?

**Comment by vicenterusso** [comment]
> Is the problem simply a floatReference? I wonder how other users have solved this problem and are using it. In 1.6.4, the GUI is broken and there are issues in the release log of 1.7.0; 1.7.0 has this issue. It has been 7 months since the issue was opened. Are the others still using 1.6.4?

I think people moved to [Unity Atoms](https://github.com/AdamRamberg/unity-atoms)

**Comment by seoyeon01** [comment]
> > Is the problem simply a floatReference? I wonder how other users have solved this problem and are using it. In 1.6.4, the GUI is broken and there are issues in the release log of 1.7.0; 1.7.0 has this issue. It has been 7 months since the issue was opened. Are the others still using 1.6.4?
> 
> I think people moved to [Unity Atoms](https://github.com/AdamRamberg/unity-atoms)

Thank you. I'll check it out : )

**Comment by DanielEverland** [comment]
Apologies for the inactivity. I've been really busy and unfortunately haven't been able to find the time to update SO-A for a while. The issue was two-fold:
1. The variable didn't respond to being edited by the editor and therefore didn't realise its property had been changed
2. There were some inconsistencies in terms of when the variable would invoke its own event and when it would invoke events on listeners, which is what the BaseEventListener uses.

I've fixed both of these issues and they so this issue should be resolved in 1.8.0

Once again, I apologize for the inactivity. I'll try fix issues more swiftly in the future :)

![](https://i.imgur.com/rp4OnU4.gif)
