### ISSUE TITLE
Game Event Listener doesn't work in play mode

### ISSUE THREAD

**Issue by nintendaii** [DanielEverland/ScriptableObject-Architecture#148]
Hi. I followed the wiki guide to create a simple event listener for PlayerCurrentHealth float variable. Idk why but when I try to change the variable in editor during play it doesn't call the event(see the attached gif). Also it doesn't destroy the game object when the value smaller than 0. Is that a bug or am I missing something?
Here is my script
```c#
    [SerializeField]
    private Image fillImage = null;
    [SerializeField]
    private FloatReference currentHealth = null;
    [SerializeField]
    private FloatReference maxHealth = null;

    private void Awake()
    {
        currentHealth.Value = maxHealth.Value;
    }
    
    private void Update()
    {
        fillImage.fillAmount = Mathf.Clamp01(currentHealth.Value / maxHealth.Value);
    }

    public void HealthChanged()
    {
        Debug.Log("yenki" );
        if (currentHealth.Value<0)
        {
            Destroy(gameObject);
        }
    }
``` 
![ScriptableObjectArchitectureDemo - SampleScene - PC, Mac   Linux Standalone - Unity 2020 1 17f1 Personal _DX11_ 2021-04-13 18-57-27](https://user-images.githubusercontent.com/44233090/114584433-57a8ce80-9c8b-11eb-9df8-d07fee69e127.gif)
![зображення](https://user-images.githubusercontent.com/44233090/114585498-63e15b80-9c8c-11eb-817c-1b1e1b506184.png)

**Comment by DanielEverland** [comment]
Are you using the newest revision from Github? I recently fixed an issue with variables not raising events :) #132

![](https://i.imgur.com/DxP4H6e.gif)

**Comment by nintendaii** [comment]
Just downloaded the SO-A from Asset Store today. I cant find the uniypackage file of the 1.8.0 release, it is empty (https://github.com/DanielEverland/ScriptableObject-Architecture/milestone/15). So should I download the project directly from git or you will update the release soon?
It is very strange that the event is actually called at the start of the game when I set the value to maxHealth a the Awake method 
```c#
private void Awake()
    {
        currentHealth.Value = maxHealth.Value;
    }
```

**Comment by nintendaii** [comment]
Ok, so I downloaded the project from git. Now it works fine! Thanks for help
