### ISSUE TITLE
BaseGameEventListener:  Errors when build 

### ISSUE THREAD

**Issue by KosmoDED** [DanielEverland/ScriptableObject-Architecture#36]
![image_2018-11-05_19-42-46](https://user-images.githubusercontent.com/39064671/48016245-ca650580-e133-11e8-8f05-84af9fd081e4.png)

I managed to remove highlighted error from first picture (lines marked with // kosmoded)
![image](https://user-images.githubusercontent.com/39064671/48016315-f54f5980-e133-11e8-934f-2d78bd7a5733.png)

Don’t know how to remove other errors.

**Comment by DanielEverland** [comment]
Thanks for the report, that's an oversight on my part. Pushed a hotfix which resolves all build errors

https://github.com/DanielEverland/ScriptableObject-Architecture/releases/tag/v.1.4.1.1
