### ISSUE TITLE
DebuggableGameEventListener: Create Debug entry null reference exeption when destroying 

### ISSUE THREAD

**Issue by KosmoDED** [DanielEverland/ScriptableObject-Architecture#37]
I was in need to destroy gameObject stored in GameObject Variable, so I created Destroy Method.
![image](https://user-images.githubusercontent.com/39064671/48085850-18e1d500-e204-11e8-89b1-43592bb0327e.png)

However, after that I received error like this.
![image](https://user-images.githubusercontent.com/39064671/48085826-09fb2280-e204-11e8-9d03-4f7c161e7dec.png)

To resolve this problem I added selected code from picture below.

![image](https://user-images.githubusercontent.com/39064671/48085755-d61ffd00-e203-11e8-83c2-eba3eabf1242.png)

I think it’s not an issue at all, but maybe in future when somebody will decide to Destroy gameObject that stored in GameObjectVariable with some script he can have error like me. 

![image](https://user-images.githubusercontent.com/39064671/48086989-d372d700-e206-11e8-9973-33db04c33c00.png)
[usecase that caused error]

P.S. Thank you for this project, its very helpfull for me.

**Comment by DanielEverland** [comment]
Resolved, it'll be included in 1.4.2

Thanks for the report and the kind words :)
