### ISSUE TITLE
UniRx integration

### ISSUE THREAD

**Issue by JonnyBGod** [DanielEverland/ScriptableObject-Architecture#45]
Would you consider integration with UniRX?

Reference project: https://github.com/Wolar-Games/unity-scriptable-object-variables

**Comment by DanielEverland** [comment]
I haven't used UniRX before, could you quickly outline what would need to be implemented? Is it just the ability to subscribe to events as shown here: https://github.com/Wolar-Games/unity-scriptable-object-variables/blob/master/Source/Views/GameObjectToggle.cs

**Comment by JonnyBGod** [comment]
I would start with:
- https://github.com/Wolar-Games/unity-scriptable-object-variables/blob/master/Source/Variables/Variable.cs
- https://github.com/Wolar-Games/unity-scriptable-object-variables/blob/master/Source/Variables/Reference.cs

I come from the web world and am quite new to unity and c# but how I usually do it is something like this:

```
public T value { get { return _value; } set { _value = SetValue(value); } }
public ReactiveProperty<T> value$ { get; private set; } = new ReactiveProperty<T>(value);

public SetValue(value) {
  value$.SetValue(value);
  return value;
}
```

```value``` would be a regular variable while ```value$``` would be an observable.
This way you get the flexibility to use the variable the way the best fits your needs in any given case.

Note: I am not completely confident ```ReactiveProperty``` is the best option here.

**Comment by DanielEverland** [comment]
I'm very much from the C# and Unity world, and am not quite sure what an observable contains. Skimming an article from a Google search leads me to believe it allows you to subscribe to variables, receiving a callback whenever the value changes. Is that correct? If so, what would a UniRX integration allow, that simply adding such functionality wouldn't?

FYI that does sound useful, would be neat if ScriptableObject-Architecture event listeners could subscribe to variables directly. Unity serialization doesn't handle such a relationship well, but I think I'll be able to figure out a solution. #46

**Comment by JonnyBGod** [comment]
Using a Rx library gives you a lot of operators to work with your observables.
Providing a way to subscribe to changes is very useful in it self but having all needed operators to work with your observables make it very powerful.

Have a quick look at all exemples at https://github.com/neuecc/UniRx readme.
And try to think how would you do that without the provided operators and just a simple subscriber model.

You will find out that you would need a lot of boilerplate code and worst, a bunch of hacks.

**Comment by JonnyBGod** [comment]
http://reactivex.io/documentation/operators.html these are all operators common to most Rx implementations.

Enfase os combine operators that are very useful to control your flow and are not trivial to accomplish with just a simple subscriber model.

**Comment by JonnyBGod** [comment]
I could probably study this better and work on a PR. But because I am only doing this a few hours per day at night, it might take some time.

If you like the idea I can help you reviewing your PR and testing.

**Comment by JonnyBGod** [comment]
From my perspective once I got into reactive programing for the web I would never go back.
It makes a lot of sense once you get the gist of it.
And for this particular library that on my understanding wants to promote good data flow architectures, Rx is best way we have atm.

It might be helpful to also learn a bit about https://facebook.github.io/flux/ and https://redux.js.org/. These come from the web world but I don't see why not apply it to the game world. https://www.youtube.com/watch?v=yU8-mDhawEw

**Comment by DanielEverland** [comment]
It certainly has some nice features, but to be frank, I don't see myself using this in my core architecture. If a PR is posted, either by you or someone else, I definitely wouldn't mind merging it. I primarily spend my time working on my game, and I don't have the time to implement a large feature I won't use myself.

I definitely appreciate the recommendation, though :)

**Comment by JonnyBGod** [comment]
Fair enough :)

I will play a bit with this and once I feel comfortable will provide a PR.
