### ISSUE TITLE
Serialization Issue with WebGL

### ISSUE THREAD

**Issue by AlexKnowles** [DanielEverland/ScriptableObject-Architecture#49]
Hello,

I had an issue with using your architecture with WebGL, specifically:
`A scripted object (probably DanielEverland.ScriptableObjectArchitecture.Events.Listeners.Vector3GameEventListener?) has a different serialization layout when loading. (Read 340 bytes but expected 352 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?`

![firefox_qfq4u6atam](https://user-images.githubusercontent.com/25254827/51804697-0a7fe400-225c-11e9-8530-531b68f134e5.png)

This only seems to happen when I build and run (which reinforces the "Did you #ifdef UNITY_EDITOR a section…" bit). I've been able to fix the issue by removing `#if UNITY_EDITOR` from the serialized field `_debugValue` in the `GameEventBase` and `BaseGameEventListener` classes.

I thought I’d raise an issue just in case someone else experiences it. Probably won't cause too much harm by having some unused serialized fields in a build…

Oh, also, I may have done something a bit strange by putting your repo / code into its own namespace and Assembly Definition in Unity (So I can use it with unit tests). I’m certain this didn’t cause the problem but it’s probably worth noting. For reference, source is here: https://github.com/AlexKnowles/MineColony/tree/develop/Assets/ThirdParty/SO%20Architecture

Thanks for creating such an awesome free asset!

**Comment by DanielEverland** [comment]
I was able to reproduce the issue, and after doing some research, it seems like Unity generally doesn't like when you exclude serialized fields from a build. It'll be fixed in the next release, which I expect to be available today.
