### ISSUE TITLE
Events triggered twice at Awake.

### ISSUE THREAD

**Issue by Thejoness** [DanielEverland/ScriptableObject-Architecture#50]
Hi Daniel, I like your library, but I have a problem where my events triggers twice upon an invoke. I only have a single EventListener on the GameObject. I have only discovered this bug trigger from the Start / Awake function. Do you know about this issue?

Best Jonas

**Comment by DanielEverland** [comment]
I'll look into it :)

In the meantime could you provide some more concrete steps to reproduce? A sample project where the issue is present would also be very helpful

**Comment by Thejoness** [comment]
Hi Daniel

I figured out that "OnValidate" and "OnEnable" both triggers at Startup. Therefore, all the listeners were registered multiple times. I commented out "OnValidate", will that cause any troubles later on?

**Comment by DanielEverland** [comment]
Thanks for the reply, you're correct in saying that the OnValidate registration is unnecessary. Should be safe to comment out, I'm also pushing out a release sometime later today where it's been fixed :)

Thanks for the report!
