### ISSUE TITLE
Inspector Rendering Issue for References

### ISSUE THREAD

**Issue by JeffWeber** [DanielEverland/ScriptableObject-Architecture#54]
I'm getting some very strange rendering issues. The attached image
 is from one of your examples.

You can see that the UI for the float reference is showing up underneath the item below it.  Happens for other variable/refernce types as well

![Capture](https://user-images.githubusercontent.com/1037453/55668090-44580280-582a-11e9-87f6-bb554874341d.JPG)

This is in: Unity 2018.3.11f1

**Comment by DanielEverland** [comment]
Did you change the source code of the asset at all?

If you send me your project to daniel@everlandgames.com I'll take a look at it :)

**Comment by JeffWeber** [comment]
No, I did not change the source at all. I'll try creating a new project and see if it happens. Not feasible to send my whole project.

**Comment by JeffWeber** [comment]
I figured out the issue. I had an Editor in my code that worked for all ScriptableObjects so it was conflicting with your editors.  Sorry to bug you. Nice Asset!

**Comment by DanielEverland** [comment]
No worries, glad you got it resolved! :)
