### ISSUE TITLE
Namespace needed

### ISSUE THREAD

**Issue by rgardler** [DanielEverland/ScriptableObject-Architecture#55]
The lack of a namespace makes it difficult to reuse this code in complex applications.

**Comment by DanielEverland** [comment]
Been meaning to implement it, thanks for giving me an excuse to do so ^^

**Comment by DanielEverland** [comment]
https://github.com/DanielEverland/ScriptableObject-Architecture/releases/tag/v1.5.4

**Comment by rgardler** [comment]
Nice. Thank you.
