### ISSUE TITLE
Feature Request: Package Distribution

### ISSUE THREAD

**Issue by jeffcampbellmakesgames** [DanielEverland/ScriptableObject-Architecture#61]
Hi Daniel, now that Unity 2018.3 and later now support downloading git-based packages (with better support incoming with 2019.1 and more in the future) would you have any interest in distributing a version of this tool in that format? I have an MIT open source Unity editor tool found [here](https://github.com/jeffcampbellmakesgames/unity-package-tools) that can help support this by:
* Providing a configuration asset and one-click mechanism to update package source when making a release.
* Can itself be imported as a package and not included with the repository contents (packages are downloaded to the Library folder). 
* Serves as a good example of how to distribute a Unity library as a package, has its own package release branch that mimics how to use the tool. 

I was planning on making a package of this library for my own personal development on my fork, but it might be something worth considering in the future on the main repo as it makes it easier for users to get the latest updates of a library while at the same time make it easier to update library content for users without having to resolve conflicts (downloaded packages are immutable from direct user-editing when imported this way and their contents are cleared out entirely when updating to a different version). 

I believe this is a great implementation of scriptable architecture, thanks for providing it on GitHub as MIT open source!

**Comment by DanielEverland** [comment]
Definitely, I'm a big fan of the new package manager. I'll set it up right away and let you know if I have any questions

And thanks, I'm glad you enjoy it! Thanks for providing the PR's, they're always much appreciated and well implemented! :)

**Comment by DanielEverland** [comment]
As you might've seen, I'm having trouble importing your tool. Full report here: https://github.com/jeffcampbellmakesgames/unity-package-tools/issues/1

**Comment by jeffcampbellmakesgames** [comment]
> As you might've seen, I'm having trouble importing your tool. Full report here: [jeffcampbellmakesgames/unity-package-tools#1](https://github.com/jeffcampbellmakesgames/unity-package-tools/issues/1)

Thanks for the info, I will resolve this and comment back on here/the issue once its resolved.

**Comment by DanielEverland** [comment]
Done
