### ISSUE TITLE
Some Unity struct types do now allow edit-time modification

### ISSUE THREAD

**Issue by jeffcampbellmakesgames** [DanielEverland/ScriptableObject-Architecture#66]
### Summary
There is currently a bug with the Inspector/Drawers for editing Reference constant, variable, or collections of Vector4 and Quaternion where only a foldout is shown with no editable fields (tested on 2019.1.0f2). 

I have resolved this drawing issue by adding some hardcoded checks to `GenericPropertyDrawer` (for layout and non-layout methods) to check for these types and show the appropriate controls and changing the `BaseReferenceDrawer` to use this helper class, but the work is based on PRs https://github.com/DanielEverland/ScriptableObject-Architecture/pull/57 and https://github.com/DanielEverland/ScriptableObject-Architecture/pull/65 so I would wait until those are merged prior to making another PR.

## Before

**Vector4Variable**
![image](https://user-images.githubusercontent.com/1663648/56453865-bfe8a200-6348-11e9-9e99-96c007253029.png)

**QuaternionCollection**
![image](https://user-images.githubusercontent.com/1663648/56453882-f7574e80-6348-11e9-9a1a-a05e7da9888e.png)

**Example script with various references**
![image](https://user-images.githubusercontent.com/1663648/56453860-a7788780-6348-11e9-908b-33739b4f7bd1.png)

## After

**Vector4Variable**
![image](https://user-images.githubusercontent.com/1663648/56453754-0c32e280-6347-11e9-9bd8-61bf149ddee7.png)

**QuaternionCollection**
![image](https://user-images.githubusercontent.com/1663648/56453752-02a97a80-6347-11e9-967b-a7dfd84feac4.png)

**Example script with various references**
![image](https://user-images.githubusercontent.com/1663648/56453932-9c722700-6349-11e9-81a4-f60a7849f509.png)

**Comment by DanielEverland** [comment]
There's still a couple of issues that I've confirmed aren't related to #68 

There's a bit of a gap between the reference button and the following field
![](https://i.imgur.com/RDOmMGS.png)

Constant values expand across several lines
![](https://user-images.githubusercontent.com/5272590/56475842-6a1e1200-648e-11e9-8418-de6851d5a4f0.png)

**Comment by jeffcampbellmakesgames** [comment]
### Padding
> There's still a couple of issues that I've confirmed aren't related to #68
> 
> There's a bit of a gap between the reference button and the following field
> ![](https://camo.githubusercontent.com/1c9bfb32f22234ab7a8ed5cbc75c86e3b08328f8/68747470733a2f2f692e696d6775722e636f6d2f52444f6d4d47532e706e67)
> 
> Constant values expand across several lines
> ![](https://user-images.githubusercontent.com/5272590/56475842-6a1e1200-648e-11e9-8418-de6851d5a4f0.png)

The gap is related to the fix for the bug with that popup style mentioned here https://github.com/DanielEverland/ScriptableObject-Architecture/pull/57#issuecomment-484783591.  Essentially when in a list that Popup button is being obscured by the propertyfield next to it which is somehow extending past the beginning of its rect (internal to Unity, our calculations seem fine), thus rendering it unclickable.  I mitigated this issue by giving the popup button a width that includes its own width + buffer for the indent level. This results in there being a slight margin between the end of the rect for the popup and propertyfield, but allows the popup to remain clickable whether in a list or as a single field. I've added some screenshots here showing a pink box for the constant/variable propertyfield and how it interferes with the popup button, with and without the fix.

**WithoutFix**
![image](https://user-images.githubusercontent.com/1663648/56489560-66b47600-64e2-11e9-9f2e-06cfeb76641b.png)

**With Fix**
![image](https://user-images.githubusercontent.com/1663648/56489380-d37b4080-64e1-11e9-941b-56743eb11686.png)

This behavior is something internal to the EditorGUI controls for vector fields which we likely are not going to be able to fix easily. One possible solution is to write our own EditorGUI Vector field methods which would allow us to more tightly control the spacing and avoid any blackbox behavior from the default Unity Vector field controls.

Overall the impact of this padding as a bug seems low to me, but could be mitigated with more custom editor code for these value types.

### Constant Values on Next Line

**Latest screenshot off of master for constant value drawers**
![image](https://user-images.githubusercontent.com/1663648/56489817-4a650900-64e3-11e9-882c-edfa2037981f.png)

The only time where I see constant values being placed onto the next line is where the inspector width has become small enough that the controls are not editable and being placed there. I tried some fixes to see what it would look like when it was forced to a single line, but this seems to cause a worse readability issue than symptom its trying to fix.

**With fix to set single line always (less readable):**
![InlinePropertyDrawerWithoutHeightAdjustment](https://user-images.githubusercontent.com/1663648/56489117-ed685380-64e0-11e9-90bb-6bbc90b5645f.gif)

**Current behavior where constant is pushed to next line with small inspector width (more readable):**
![InlinePropertyDrawerWithHeightAdjustment](https://user-images.githubusercontent.com/1663648/56489151-0bce4f00-64e1-11e9-8293-cc8c809a9d76.gif)

**Comment by jeffcampbellmakesgames** [comment]
I created a PR here that adds a Debug GUIStyle as well as some unrelated refactoring I did while testing this. If you feel like poking at this just add `SOArchitecture_EditorUtility.DebugStyle` to any EditorGUI call you want to debug and the background color should show as a slight pink.

**Comment by DanielEverland** [comment]
I fixed the following issues
- Space between popup and value fields
- Incorrect use of multiline for primitives (Types now require the [MultiLine] attribute)
- Non-multiline fields will no longer draw beneath their labels on inspectors with low width

![inspector](https://user-images.githubusercontent.com/5272590/57020509-c7058f00-6c29-11e9-8b89-d4a1c9d84891.gif)

**Comment by Jeffrey-Campbell-Zapdot** [comment]
Nice job! Looks great
