### ISSUE TITLE
"You are trying to import an asset which contains a global game manager."

### ISSUE THREAD

**Issue by rgardler** [DanielEverland/ScriptableObject-Architecture#72]
I'm getting a couple of warnings and errors on import into my project. It may be important to know that I'm importing the code into my Git repository using Git Submodules. This shouldn't affect things, but might be relevant.

I get 14 warnings (one is a never assigned variable, I'll investigate that so ignore for this issue)

I also have three warnings that indicate XRSettngs.asset was serialized by a newer unity version (I'm on 2018.3.12f). This is likely unrelated too. But I share in case it is relevant

This issue is really about the 13 identical warnings: "You are trying to import an asset which contains a global game manager. This is not allowed."

Everything seems to work if I simply ignore these warnings, and (so far) they have only occurred on initial import, so this is a low pri issue.

**Comment by jeffcampbellmakesgames** [comment]
To make sure I'm understanding, you're importing the master branch containing its own Unity project as a submodule in another git project? Can you give us some context around why its setup this way; are you using a file package reference from another Unity project in the same folder?

The latest version of the Unity project on the master branch is running 2019.1.0f2 which is probably why you're seeing some issues if you're opening it on an earlier version of the editor.

**Comment by DanielEverland** [comment]
I'll take a look at this if you provide steps to reproduce

**Comment by DanielEverland** [comment]
Also, please see if using any of [these](https://github.com/DanielEverland/ScriptableObject-Architecture#installation) installation methods works for you

**Comment by rgardler** [comment]
Addressing comments in order...

I'm using a git submodule so I can make changes to the code should it be necessary. I want to be able to make PRs against your repo. I'd rather not have to switch out to another project make edits and then update in my main project. Hence git submodules.

That said, I'm not actually planning to make change - the only issue I've found in testing you already fixed - but I want to be set up to do so. If that doesn't make sense the repro steps in I add later will probably make it clearer.

Repro steps - note I'm using my fork of your code, but it is a clean fork of master - no reason why the result should be different using your repo.

1. Create a new project
2. cd PROJECT_FOLDER
3. git init
4. cd Assets
5. git submodule add git@github.com:DigitalPainting/ScriptableObject-Architecture.git
6. Give Unity focus so that it imports the asset

Testing using src.zip from releases into a clean project without git init result in the same error.

Testing using an the .unitypackage from release into a clean project without git init worked fine. Including not getting the Unity version error.

So it would seem the problem is related to using the source of the project within another project. 

I can work around it by using a package and importing that, or simply ignore the warnings and update this issue if I see any negative effects.

The Unity version thing is not a problem. I'm planning on moving to 2019 soon.

**Comment by rgardler** [comment]
I just confirmed this occurs with another project imported using submodules.

My suspicion is that it is related to the fact that Unity processes the ProjectSettings of the imported asset.

Either way this doesn't see to be a problem with your code, but with the way I'm using it.

**Comment by rgardler** [comment]
I've done a little research and it would appear that my assumption above is correct. What is happening is that Unity is seeing the global .asset definitions in the submodule and attempting to import them. 

If I add a step 5.5 to the repro with `rm -Rf ScriptableObject-Architecture/ProjectSettings` then the errors go away (in other words behaviour is the same as if I import using the .unitypackage.

If I find a solution to this I'll update this issue, for now I think it's best to clost this as it is not an issue with your code.
