### ISSUE TITLE
Adding any listener to an object creates NullRefException error

### ISSUE THREAD

**Issue by Leedotzip** [DanielEverland/ScriptableObject-Architecture#78]
After adding a game event listener to an object I get an error about `DrawLine()` which results in the custom inspector breaking

- Unity 2018.2.21f1

`NullReferenceException: Object reference not set to an instance of an object
ScriptableObjectArchitecture.DebuggableGameEventListener.DrawLine () (at Assets/Third Party/SO Architecture/Events/Listeners/BaseGameEventListener.cs:233)
ScriptableObjectArchitecture.DebuggableGameEventListener.UpdateDebugInfo () (at Assets/Third Party/SO Architecture/Events/Listeners/BaseGameEventListener.cs:187)
ScriptableObjectArchitecture.DebuggableGameEventListener.OnDrawGizmos () (at Assets/Third Party/SO Architecture/Events/Listeners/BaseGameEventListener.cs:180)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`

![example gif](https://i.gyazo.com/1a355aa67c471c397a41e92819fd6394.png)

**Comment by DanielEverland** [comment]
I can't reproduce your issue, could you provide Steps to Reproduce? I've tried the following
1. Create GameEvent object in project
2. Add GameEventListener to a GameObject
3. Assign the GameEvent object to the GameEventListener in the "Event" field
 > No erorr occurs

**Comment by DanielEverland** [comment]
Determined to be an issue with the users project instead of the asset
