### ISSUE TITLE
[Suggestion] Runtime ScriptableObjects

### ISSUE THREAD

**Issue by Begounet** [DanielEverland/ScriptableObject-Architecture#79]
Hello!

More than an issue, I wanted to discuss with you about ScriptableObjects variables whose the value should be changed at runtime. They are opposed to these ScriptableObjects that are used as constants.

Most of the time, with these special kinds of ScriptableObjects, we want:
- inital value
- keep the possibility of editing the value during play mode to make tests
(- perhaps also a "reset()" feature?)

The idea should be to have something like this:
![Unity ScriptableObject Runtime](https://unity3d.com/profiles/unity3d/themes/unity/images/eloqua/article/Unity-scriptable-object-float-variable2.jpg)
_From https://unity3d.com/fr/how-to/architect-with-scriptable-objects_

So I tried to do something similar (but give up with the ISerializationCallbackReceiver since the OnAfterDeserialize is called each time you change the value in the Inspector and didn't wanted this behavior).

Here is what I get:
![RuntimeScriptableObjects](https://user-images.githubusercontent.com/6328801/57707006-28385400-7667-11e9-877a-bd5077f42c39.gif)

So from the code side, I had to add 2 new variables to BaseVariable<T>:
- T _initialValue
- bool _isRuntime

So, that change increases the size the ScriptableObject by doubling the `T value`, making each ScriptableObject heavier, even if they are not set as "runtime ScriptableObjects".
An other way I can see is to make some subclasses like RuntimeFloatVariable (that inherit from FloatVariable or some kind of RuntimeVariable<FloatVariable>) but it will make a looooot of new classes and it will be harder to maintain on a long term.

So what do you think about it?

Thanks for your time and that great repository!

**Comment by DanielEverland** [comment]
This has been suggested before (#71, #51) and will not be added because it directly contradicts the convention of Unity objects.

**Comment by Begounet** [comment]
Oh, right, thank you for your answer.
Have a nice day!

**Comment by DanielEverland** [comment]
Thanks, you too :)
