### ISSUE TITLE
Constant vs Variable 

### ISSUE THREAD

**Issue by psarras** [DanielEverland/ScriptableObject-Architecture#81]
Any plans of adding a drawer similar to the one from Ryan's talk?

https://github.com/roboryantron/Unite2017/blob/master/Assets/Code/Variables/Editor/FloatReferenceDrawer.cs

**Comment by DanielEverland** [comment]
Already implemented :)

https://github.com/DanielEverland/ScriptableObject-Architecture/blob/master/Assets/SO%20Architecture/Editor/Drawers/BaseReferenceDrawer.cs
