### ISSUE TITLE
Error while select GameEvent of abstract class or interface type in editor mode

### ISSUE THREAD

**Issue by lee12321** [DanielEverland/ScriptableObject-Architecture#83]
It seems the editor doesn't work with abstract class and interface? 
While selecting GameEvent of these type it shows NullReferenceException error. Does this affect the runtime and build?

**Comment by DanielEverland** [comment]
This is not a bug, but simply how Unity's serialization works. It can't serialize interfaces, abstract classes or generic classes. This causes exceptions in the editor because it attempts to get serialized fields from your class, which do not exist
