### ISSUE TITLE
How do i pass variable types through dynamically?

### ISSUE THREAD

**Issue by TomZandt** [DanielEverland/ScriptableObject-Architecture#85]
Firstly, this is an amazing repo. Thanks for sharing!

I need a little help with passing objects through an event and recieving it in the listener?

I am unsure whether i can ask this here or not, but i thought id ask as i am unable to figure out how this is done dynamically?

I have a script for a key:
https://github.com/TomZandt/Unity_TZV_2D_Platformer/blob/master/Unity_TZV_2D_Platformer/Assets/V3/Scripts/Gameplay/V3_Key.cs

![image](https://user-images.githubusercontent.com/22413477/62664239-b4aa9800-b972-11e9-9fdb-4aac4a9451dd.png)

And a script for a manager:
https://github.com/TomZandt/Unity_TZV_2D_Platformer/blob/master/Unity_TZV_2D_Platformer/Assets/V3/Scripts/Managers/V3_GameManager2.cs

![image](https://user-images.githubusercontent.com/22413477/62664265-d3a92a00-b972-11e9-9d60-fe6834f58960.png)

in start(), the V3_Key raises an object game event to say there is a key in the scene;
![image](https://user-images.githubusercontent.com/22413477/62664059-fbe45900-b971-11e9-8cd6-a839bef2be4e.png)

The gamemanager listens for the event and trys to register the key, by adding it to an object collection.
![image](https://user-images.githubusercontent.com/22413477/62664096-26cead00-b972-11e9-8bcd-f0a5b71499f2.png)

All of this is working code wise, except my problem is i don't know how to pass the object through the event. It lets me add the key by dragging from the scene into the event listener, and thus into the object collection. However i want to dynamically pass the object through when the event is raised, not by manually assigning it in the inspector:

![image](https://user-images.githubusercontent.com/22413477/62664160-6dbca280-b972-11e9-8d3a-2b1a8eade675.png)

ie, The yellow highlight to be passed from the event call itself:
![image](https://user-images.githubusercontent.com/22413477/62664473-8a0d0f00-b973-11e9-994d-e4818350f872.png)

Hopefully that makes sense?

If you are able to help it would be greatly appreciated, otherwise simply delete this issue.

Again, thanks for all the hard work you have done so far!

**Comment by DanielEverland** [comment]
There are several types of Events, each allowing you to pass through a given type as an argument when raising. There's also a void one called GameEvent, which is the one you're using, that doesn't pass through any data.

Simply use one of the already existing ones: https://github.com/DanielEverland/ScriptableObject-Architecture/tree/master/Assets/SO%20Architecture/Events/Game%20Events (ObjectGameEvent would allow you to pass through your V3_Key type as an Object and then downcast back to V3_Key wherever you've subscribed)

You can also use the code generation window to create new events with whatever type you please automatically. This would allow you to easily create a V3_Key even so you can pass it along without any type of casting :)

**Comment by TomZandt** [comment]
Thanks for the reply, so are these not ObjectGameEvents then? I thought that was the event i was using from the existing ones you mentioned?

![image](https://user-images.githubusercontent.com/22413477/62722960-79a67400-ba07-11e9-8ed1-96dd96431059.png)

**Comment by DanielEverland** [comment]
Oh, I misread your code. I see what you're doing wrong. In the Unity inspector where you select a response, there should be two sections; dynamic parameters and static parameters - dynamic parameters are used in order to automatically pass the reference used when raising the event
![image](https://user-images.githubusercontent.com/5272590/62725777-14a64a80-ba16-11e9-80e0-e75bce1850d8.png))

If you don't have that option, it's because the target object doesn't contain a function with the correct signature. For ObjectGameEvents that would be `void functionName(UnityEngine.Object)` - I'm not sure if Unity supports inheritence in that regard, so `void functionName(V3_Key)` might be invalid even though it does inherit UnityEngine.Object

**Comment by TomZandt** [comment]
Thank you so much for the help. That worked perfectly!!

I ended up having to create my own V3_Key from the code generator and then they all popped up in the dynamic part.

![image](https://user-images.githubusercontent.com/22413477/62727551-a2336b80-ba11-11e9-884a-25b2ca3bd7e2.png)

**Comment by DanielEverland** [comment]
No problem, glad you got it working :)
