### ISSUE TITLE
"Value changed" event is called too soon if edited in inspector

### ISSUE THREAD

**Issue by hadmaerd** [DanielEverland/ScriptableObject-Architecture#86]
When you change variable's value in inspector, it triggers Target.Raise() before the value in SO is actually changed, e.g. if you have BoolVariable equal to false and click it in inspector, checkmark appears but listeners still get "false".

To fix it you should put a flag and call the event on next GUI frame that happens immediately anyway.

![5a3849cc41256a85f1e6844d753948f2](https://user-images.githubusercontent.com/6717257/62771619-51218700-baa6-11e9-8d53-c54bfd520a08.png)

**Comment by DanielEverland** [comment]
Fixed. Thanks for reporting the issue :)
