### ISSUE TITLE
Bad copy-paste bug in GameEventBase.cs

### ISSUE THREAD

**Issue by hadmaerd** [DanielEverland/ScriptableObject-Architecture#88]
at line 26 for-cycle must be iterating through _actions, not _typedActions

![c6a64eca4a571727efcff4881047e762](https://user-images.githubusercontent.com/6717257/63063954-7cbdca80-bf07-11e9-94dc-de4327f4f8bd.png)

**Comment by DanielEverland** [comment]
This is an issue on your end. Here's what the repo looks like

![](https://i.imgur.com/v5sUSy8.png)
