### ISSUE TITLE
Is it possible to handle non-singleton relationships with this architecture?

### ISSUE THREAD

**Issue by mnarimani** [DanielEverland/ScriptableObject-Architecture#90]
Three examples that is provided in this package is only showing us how we can replace Singleton variables with SO variable. 
Is it possible to use this architecture to decouple systems that have more than one instance? Like enemy? When enemy shoots, I want to raise an event, and only the receiver on that enemy should receive the event. Is it possible?

**Comment by DanielEverland** [comment]
If I understand your question correctly then, yes, that should be possible. Seeing as ScriptableObject-Architecture events simply are Unity objects, you can indeed create objects per-enemy during runtime. To do so, simply use the [ScriptableObject.CreateInstance()](https://docs.unity3d.com/ScriptReference/ScriptableObject.CreateInstance.html). If you want to base that event on a prefab, simply use [Object.Instantiate()](https://docs.unity3d.com/ScriptReference/Object.Instantiate.html) passing your prefab as a reference

You can then subscribe to the [SO-A event](https://github.com/DanielEverland/ScriptableObject-Architecture/blob/master/Assets/SO%20Architecture/Events/Game%20Events/GameEventBase.cs) using either the SO-A interface [IGameEventListener](https://github.com/DanielEverland/ScriptableObject-Architecture/blob/master/Assets/SO%20Architecture/Events/Listeners/IGameEventListener.cs) or a standard C# Action

I haven't used it in this way before, though. If you use this in an interesting way feel free to let me know, I'd like to see what such a system would look like :)

**Comment by mnarimani** [comment]
I'm using *References in the same way that you describe.
For example when I create enemy, I link enemy and its weapon with a bool reference:
```var isAttacking = new BoolReference(false);
var enemy = Instantiate(enemyPrefab);
var enemyAttacker = enemy.GetComponent<EnemyAttacker>();
var weapon = enemy.GetComponentInChildren<Weapon>();
enemyAttacker.IsAttacking = isAttacking;
weapon.IsShooting = isAttacking;
```
This way the weapon and enemy get linked to each other without knowing each other. (This is also known as Mediator pattern).

But it's only useful when you are instantiating objects. If you have multiple enemies that exist in design time, you cannot link their weapon and their attacking component. 

Ryan mentioned that Singleton has this problem that you have to revisit your model when your requirements changes. (13:30). But it seems that this pattern also has this problem.
You only can use this pattern for things that have one instance. (in editor of course). If what was single instance before becomes two or three instances, everything suddenly breaks. And you have to rework everything.
