### ISSUE TITLE
can't raise event dynamically in 2019.30b4

### ISSUE THREAD

**Issue by pbrito** [DanielEverland/ScriptableObject-Architecture#92]
It works in 2019.2
![Annotation 2019-09-26 190754](https://user-images.githubusercontent.com/1783930/65713682-9e2ade00-e091-11e9-9114-1fc55a6ddcf7.jpg)
but with  2019.30b4
![Annotation 2019-09-26 191317](https://user-images.githubusercontent.com/1783930/65713735-b995e900-e091-11e9-8a98-088bd39ff84b.jpg)

Thanks,
Great work, but I cant get it to work!

**Comment by DanielEverland** [comment]
When we spoke on Twitter, I thought this occurred in a stable Unity version. You've downloaded the beta, so I'm going to wait until release before I start looking into this issue.

I'll close it for now, but if it pops up again in a stable version of Unity, feel free to post a comment here and then I'll re-open it right away :)
