### ISSUE TITLE
More Thorough Documentation

### ISSUE THREAD

**Issue by roblovelett** [DanielEverland/ScriptableObject-Architecture#98]
I want to use this architecture, but I'm new to Unity and the documentation seems targeted towards Intermediate programmers. Although Ryan's talk is valuable, and you provided a recreation of his example scenes, a step-by-step guide making a simple game that uses all the features your architecture offers would be helpful. Nothing extravagant, just some cubes on a plane or something.

In the meantime I'll "git gud" and keep watching Ryan's talk and reading the provided docs.

**Comment by DanielEverland** [comment]
I would happily consider this if you could provide a more detailed explanation of what exactly you're missing.

Furthermore, this package can't really help you build a game, there are simply aspects of game architecture in which this can be massively helpful, so that's something to keep in mind.

**Comment by roblovelett** [comment]
> I would happily consider this if you could provide a more detailed explanation of what exactly you're missing.

Thanks for the quick response. Looking at a similar package, like Atoms, a step-by-step tutorial using the main features of your architecture (clamped and regular vars, collections, listeners and events, references).

As a for instance, I'm making a prototype of a non-player character that searches for three way-points in a specified order, does a certain action depending on which way-point it collided with, and upon hitting the maximum number of way-points, does a certain action and the game ends. Right now I created a state machine using interfaces, but this seems overly complex when I could use a collection of events with your architecture.

**Comment by DanielEverland** [comment]
That makes a lot of sense, thanks for posting an example. I'll look into writing a similar guide for SO-A that utilizes all of its features :)

**Comment by DanielEverland** [comment]
I've slowly started working on it here: https://github.com/DanielEverland/ScriptableObject-Architecture/wiki/Quick-Start

I'll close this issue when the page is complete

**Comment by DanielEverland** [comment]
'Aight, it's done. Hope you find the tutorial useful, thanks for requesting it! :)
